services:
  php-apache:
    image: php:8.1-apache
    container_name: ecommerce-php
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:5.6
    container_name: ecommerce-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ecommerce-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: ecommerce_user
      PMA_PASSWORD: userpassword
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
